### ISSUE TITLE
WQHD Support

### ISSUE THREAD

**Issue by ghost** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#10]
Hello,

absolutely awesome resource. Is WQHD support being considered in the near future? Unfortunately, it looks a bit "warped".

https://i.epvpimg.com/jN5Gbab.png

**Comment by rohKane** [comment]
Unfortunately i don't have 2k or 4k monitor to adjust the hud to fit it but you can enable this it will force your UI to be 1920x1080.

https://forum.cfx.re/uploads/default/original/4X/7/a/5/7a563bce9a8eefee779d6416078f3a8ef7c75df7.jpeg
