### ISSUE TITLE
Non Bug (ui issue)

### ISSUE THREAD

**Issue by DoubleDxx** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#12]
But Maybe next update for aircraft, because the hud not clear for aircraft
![Screenshot (167)](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/102321644/c3b06c32-8336-4fad-b244-f1a123f21291)

**Comment by DoubleDxx** [comment]
and oxygen not work

**Comment by rohKane** [comment]
Oxygen works when you are swimming.
