### ISSUE TITLE
hud ui issue

### ISSUE THREAD

**Issue by NightRider18133** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#13]
When you first fly in and get in a vehicle everything works. if you get out of the vehicle and get back in the speedometer will not show

**Comment by Requuet** [comment]
I seem to be having the same problem! I have to re-ensure to make it work again, every time.

**Comment by NightRider18133** [comment]
https://streamable.com/mz59qs 

here is a video for refrence

**Comment by rohKane** [comment]
Fixed.
