### ISSUE TITLE
Gear HUD

### ISSUE THREAD

**Issue by abesarrr** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#16]
How to do it when the gear is automatic but the hud gear still runs like manual?

**Comment by rohKane** [comment]
Any preview?

**Comment by abesarrr** [comment]
When the vehicle is in auto mode the gear indicator should remain at a number like this. In your script, the indicator is only A
![IMG_20240116_135157](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/29142147/308c4850-aa7c-492b-a282-f41e8637c7b2)

**Comment by rohKane** [comment]
Not planned.

**Comment by rohKane** [comment]
It makes no sense to make gear display for an automatic vehicle.
