### ISSUE TITLE
HUD issue

### ISSUE THREAD

**Issue by DoubleDxx** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#17]
https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/102321644/5a48e174-249c-4469-8ebb-58d8f4e2ab17

in first vehicle its work, second vehicle not work

**Comment by regg1ekr4y** [comment]
Hi I can agree with this as well. I'm getting reports of when people swap vehicles the speedometer disappears. The only fix for them is a log out and in again. This is a new found issue from within the last 24 hours, before that it was working perfect.

**Comment by rohKane** [comment]
Download my new commit, bro. I already fixed this yesterday.

**Comment by rohKane** [comment]
Fixed.
