### ISSUE TITLE
Menu Issue

### ISSUE THREAD

**Issue by SQUIDzillaNFT** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#18]
Having a problem when you press I or do / command. the menu opens perfectly. the menu works fine but when you press escape the menu closes and its not getting rid of the cursor. you have to either close the game completely or reset the resource for the Hud so be able to do anything further.  

I did look in the app.js and client.lua where the NUI callbacks are and it all seems to be right, so I'm not sure why that happens.

**Comment by rohKane** [comment]
Try download my new commit. And ask other player if they experience the same issue or not because i can confirm it's not because of my script.

**Comment by rohKane** [comment]
Do you still have the issue?

**Comment by SQUIDzillaNFT** [comment]
ill try it again and report back
