### ISSUE TITLE
Vehicle HUD bug

### ISSUE THREAD

**Issue by xsavage995** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#19]
When I get out of the car and get in again vehicle hud won't show up again until restarting the script tried everything to make it work but did not do it. 
Using cdn-fuel as my fuel script instead of LegacyFuel even though tried it with both and the same problem happened.

**Comment by aqade** [comment]
> When I get out of the car and get in again vehicle hud won't show up again until restarting the script tried everything to make it work but did not do it. Using cdn-fuel as my fuel script instead of LegacyFuel even though tried it with both and the same problem happened.

Did you solve the issue, if so. What did you do ?
