### ISSUE TITLE
Veh Hud icons

### ISSUE THREAD

**Issue by Dzurko18** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#21]
Just got the latest update, icons arent updating and the Vehicle HUD doesnt show for alot of players.

**Comment by rohKane** [comment]
Are you sure you don't have duplicated resource? Search for any duplicated qb-hud resource and install it again because this issue has been solved.

**Comment by rohKane** [comment]
Fixed Hud not updating on player joined.
