### ISSUE TITLE
Refreshing while in Vehicle

### ISSUE THREAD

**Issue by JacksonDevelopment08** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#24]
When you reset your hud while sitting in your vehicle the Speedometer does not show back up until you relog. It will also not show up until you hit the gas if you reset the hud while outside the vehicle. Let me know if you need any more information. Thanks for everything yall do and this is a very good looking hud.

**Comment by rohKane** [comment]
To reset your Hud just press esc into pause menu and Un pause it, the Hud will reset you don't have to use command to reset it or reset it in /menu. I added this function 2 days ago.

**Comment by JacksonDevelopment08** [comment]
Sounds good!

**Comment by JacksonDevelopment08** [comment]
Also any idea why the hud does this? 

https://gyazo.com/dd5bd51a9a2932ee258e3bd915eb7a93

**Comment by rohKane** [comment]
Look for duplicated mini map stream file if you are using colored stream mini map try deleting it. Or maybe try delete minimap stream file in qb-hud.
