### ISSUE TITLE
hud not updating

### ISSUE THREAD

**Issue by gitgaming21** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#26]
so just been using the hud for a bit now and im seeing soemthing happen when you hit esc and come back out off the esc menu the hud dont light up as much as it was befor 
hud at start 
![image](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/86384399/7b4fbe81-c64c-4980-a564-d9e9e7670e04)
now hud after going into the esc menu and back out 
![image](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/86384399/dd8ca4a3-a8e7-4291-8dda-2079cf7a28eb)

this will only then go back to normal after using a item or talking in game

**Comment by rohKane** [comment]
PLEASE DOWNLOAD THE LATEST VERSION FIRST BEFORE MAKING AN ISSUE THIS HAS BEEN FIXED A LONG TIME AGO.

**Comment by gitgaming21** [comment]
il try that then

**Comment by rohKane** [comment]
Thank you.
