### ISSUE TITLE
Manual Gears not working properly

### ISSUE THREAD

**Issue by zexproof** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#27]
I have latest version. I tried driving Sultan, and in first gear go like it's automatic. Like there is no gears. I'm using ps-fuel. 

**This error show up only when I reach around 52 kph:** 
![Screenshot 2024-01-22 203911](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/81471625/3de5da61-a605-40a7-9b80-66e6e067a69e)

**Picture showing I drive 106 kph in first gear**
![Screenshot 2024-01-22 203943](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/81471625/8cac0121-3777-40a9-a2fd-2af4f5c4ab9c)

Restarting qb-hud in console fix this issue with gears, but It does not show up fuel anymore.

**Comment by rohKane** [comment]
Change it to LegacyFuel

**Comment by rohKane** [comment]
Also never start or restart the script while you are in a manual vehicle.

**Comment by rohKane** [comment]
Tested manual and there's no issues like you describe don't open an issue if you are not sure about it.
