### ISSUE TITLE
1st gear topspeed

### ISSUE THREAD

**Issue by Mattijs-Pronk** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#28]
First of all nice resource!

One thing I came across is that when you put your manual car in first gear you can reach the top speed really easily.
All the other gears work great but when remaining in first gear the car keeps going until top speed is reached.
I tried it with the Sultan standard gta5 car.

**Comment by rohKane** [comment]
Tested and mine didn't even go above 61
