### ISSUE TITLE
vehicle modifiers dont work

### ISSUE THREAD

**Issue by TheCrystalRoleplay** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#29]
Ok so in order for the hud to work correctly and not allow you to go 200mph in first gear you have to enable set max vehicle speed. by doing this it disables all mechanical upgrades including tx and admin menu /maxmods it locks it to whatever speed is in the handling.meta

**Comment by rohKane** [comment]
What issue are you facing exactly?

**Comment by NightRider18133** [comment]
I have the same issue its a problem with the manual transmission script it has a built in max vehicle speed function and it doesnt recognize when i do performance upgrades it forces the car to stay at the same max speed no matter what

**Comment by NightRider18133** [comment]
i belive Its line 190 in the hrsgears that is causing it but if you -- it out then the car will go max speed in first gear

**Comment by DarkBytesx** [comment]
> ![image](https://private-user-images.githubusercontent.com/72841575/302506817-76c6039c-1bc2-4e38-a215-bf56bb62a58b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNjg3NTIsIm5iZiI6MTcwNzI2ODQ1MiwicGF0aCI6Ii83Mjg0MTU3NS8zMDI1MDY4MTctNzZjNjAzOWMtMWJjMi00ZTM4LWEyMTUtYmY1NmJiNjJhNThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDAxMTQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkN2FjNWIzNmY3M2NiY2I1NGIzZDNkYTc4NzljMWMzYmRlNmVhNDkzMzdmOWZlOTg3ZjkyYThlMGJjYzhiYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ZAtCnntc5VqWqeiiddJ0S8NcrY06ioakBckNB8R3qQ) im using qbox and it using ox_fuel by default can someone help me get this hud to work pls lastFuelCheck = math.floor(exports['LegacyFuel']:GetFuel(vehicle))

Legacy Fuel Must Start First Before the qb-hud

**Comment by poolshark120502** [comment]
> > ![image](https://private-user-images.githubusercontent.com/72841575/302506817-76c6039c-1bc2-4e38-a215-bf56bb62a58b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNjg3NTIsIm5iZiI6MTcwNzI2ODQ1MiwicGF0aCI6Ii83Mjg0MTU3NS8zMDI1MDY4MTctNzZjNjAzOWMtMWJjMi00ZTM4LWEyMTUtYmY1NmJiNjJhNThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDAxMTQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkN2FjNWIzNmY3M2NiY2I1NGIzZDNkYTc4NzljMWMzYmRlNmVhNDkzMzdmOWZlOTg3ZjkyYThlMGJjYzhiYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ZAtCnntc5VqWqeiiddJ0S8NcrY06ioakBckNB8R3qQ) im using qbox and it using ox_fuel by default can someone help me get this hud to work pls lastFuelCheck = math.floor(exports['LegacyFuel']:GetFuel(vehicle))
> 
> Legacy Fuel Must Start First Before the qb-hud

yes but i wanna use ox fuel not legacy...

**Comment by DarkBytesx** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/72841575/302506817-76c6039c-1bc2-4e38-a215-bf56bb62a58b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNjg3NTIsIm5iZiI6MTcwNzI2ODQ1MiwicGF0aCI6Ii83Mjg0MTU3NS8zMDI1MDY4MTctNzZjNjAzOWMtMWJjMi00ZTM4LWEyMTUtYmY1NmJiNjJhNThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDAxMTQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkN2FjNWIzNmY3M2NiY2I1NGIzZDNkYTc4NzljMWMzYmRlNmVhNDkzMzdmOWZlOTg3ZjkyYThlMGJjYzhiYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ZAtCnntc5VqWqeiiddJ0S8NcrY06ioakBckNB8R3qQ) im using qbox and it using ox_fuel by default can someone help me get this hud to work pls lastFuelCheck = math.floor(exports['LegacyFuel']:GetFuel(vehicle))
> > 
> > 
> > Legacy Fuel Must Start First Before the qb-hud
> 
> yes but i wanna use ox fuel not legacy...

change export to ox_fuel

math.floor(exports['ox_fuel']:GetFuel(vehicle))
