### ISSUE TITLE
some possible bugs that I found

### ISSUE THREAD

**Issue by NathanVRZ** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#3]
Hi, I found possible bugs

- Even when I put the driver on, the hud still shows that I'm not wearing a seat belt, even with the harness on, and this gives rise to the problem of stress growing while the player is driving, even with the driver on.

- the menu also has a delay when selecting options, when you press to disappear the compass and the street name appear and then you press to appear they do not appear

**Comment by rohKane** [comment]
Hi, firstly the seatbelt and harness seem to be working fine for me and if you want the driver to not get stress under certain speed increase **MinimumSpeed** in config file like the image down here.
 
![Screenshot 2024-01-07 154619](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/47999933/82b11587-cde8-46a0-87da-f08c8d59d6f6)

Secondly the menu is not delay it's because compass and the street name only update after you close the menu it's working the same way as the original did, I didn't edit anything's beside css, html and js.

**Comment by NathanVRZ** [comment]
About the menu ok, I understood that, the issue with the belt is that it still bothers me, because even when I put the belt on it appears that I don't have the belt but I will try to find a solution here

**Comment by rohKane** [comment]
> About the menu ok, I understood that, the issue with the belt is that it still bothers me, because even when I put the belt on it appears that I don't have the belt but I will try to find a solution here

https://github.com/qbcore-framework/qb-smallresources
download newest version of this script then replace it with your old one

**Comment by rohKane** [comment]
Or maybe it's because you are using a different seatbelt script then try put this code under the function where it toggle seatbelt

```TriggerEvent("seatbelt:client:ToggleSeatbelt")```

**Comment by NathanVRZ** [comment]
Well, TriggerEvent is already in my qb-smallresource, but I will clear both my cache and the server to test, but I will also send the printout and a video of how it works for me

**Comment by NathanVRZ** [comment]
![image](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/61557181/e4ed5a1d-585d-4772-9ae6-fd0b22e996aa)

This is how it looks for me, even with feeling, the icon appears that the character is without feeling

**Comment by salt370** [comment]
why when hitting a pole going 100MPH with just the seatbelt do I not get thrown from the vehicle?

**Comment by rohKane** [comment]
> why when hitting a pole going 100MPH with just the seatbelt do I not get thrown from the vehicle?

You are not going fast enough I test this while going 180 and I got ejected out of the vehicle.

**Comment by rohKane** [comment]
> why when hitting a pole going 100MPH with just the seatbelt do I not get thrown from the vehicle?

Also please keep in mind that I change the speed from mph to kph you can change it back to mph in config.

**Comment by ArtysV** [comment]
> Well, TriggerEvent is already in my qb-smallresource, but I will clear both my cache and the server to test, but I will also send the printout and a video of how it works for me

Well, I have same problem like yours

**Comment by Dekwer** [comment]
If you still have this problem, try to change your keybind and set it back to the same you had, worked for me
