### ISSUE TITLE
[BUG] HUD elements misaligned on other resolutions 

### ISSUE THREAD

**Issue by brunoodle** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#31]
On any resolution that isn't 1920x1080, HUD elements are misaligned and can't be fixed, even if you adjust the safezone. Any way to fix this? The attached image is what the HUD looks like on 2560x1440. 
![fRIaJYL](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/71146760/225c387d-22c2-4205-8a17-fda2472db3c6)

**Comment by rohKane** [comment]
Like i said before since I don't have any 2k or 4k monitor i can't make it fit those screen you have to adjust the code yourself.
