### ISSUE TITLE
[BUG] Restarting HUD in vehicle breaks speedometer 

### ISSUE THREAD

**Issue by brunoodle** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#33]
As the title says, if you open the HUD menu and click reset HUD while inside a vehicle, it will cause the speedometer and other vehicle HUD elements to disappear. Restarting it again or from outside the vehicle does not fix it. Only way I can fix it is either relogging or restarting the resource itself.
![Wn1ApUq](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/71146760/65862250-fa16-4a0a-ab99-326df4b0c88f)

**Comment by rohKane** [comment]
Just don't reset it in the menu because I already make the Hud reset every time you enter pause menu and exit
