### ISSUE TITLE
ox fuel

### ISSUE THREAD

**Issue by poolshark120502** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#35]
add ox fuel support and when i do i or menu and closed out im stuck and have to restart?

**Comment by poolshark120502** [comment]
hud still shows KPH after setting show MPH to true and clearing server cache pls help

**Comment by rohKane** [comment]
> hud still shows KPH after setting show MPH to true and clearing server cache pls help

you need to also change it inside html
