### ISSUE TITLE
HUD size issue?

### ISSUE THREAD

**Issue by NickBroughton** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#37]
I'm in 4k currently 
<img width="519" alt="Screenshot 2024-02-25 160644" src="https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/88165525/d04154ca-51cb-4586-9e25-74961903d6bf">

**Comment by NickBroughton** [comment]
Figured out it is due to 4k... looks fine at 1080p which means it needs 2k / 4k support?

**Comment by rohKane** [comment]
fixed thank
