### ISSUE TITLE
Stress doesn't work

### ISSUE THREAD

**Issue by chiwanay** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#38]
hello, im using the latest qb-core and tried everything inside qb-hud to see if i can fix it or not

i literally just start shooting for 2 minutes and also drive for 10 minutes with the highest speed possible and i didn't get a single stress

**Comment by rohKane** [comment]
It's working fine for my server maybe try it on a new server

**Comment by rohKane** [comment]
Also try install the original hud back and see if the stress still working or not if not then there's a problem with your server

**Comment by chiwanay** [comment]
okay let me try

**Comment by chiwanay** [comment]
i re-installed the server and now Oxygen doesn't work... KEKW

**Comment by chiwanay** [comment]
can you do it with ps-hud? like instead of qb-hud
