### ISSUE TITLE
Is there a way to remove the Speedometer and Fuel blips and stuff?

### ISSUE THREAD

**Issue by spanxurazz** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#39]
So I am looking to disable the fuel and speedometer blip and the code that makes them function as I use Jim Mechanics and this comes with a speedometer already installed.... Is there a way to do this?

**Comment by rohKane** [comment]
What do you mean by speedometer blip?

**Comment by spanxurazz** [comment]
The speedometer? Where it shows the speed of the vehicle?

**Comment by rohKane** [comment]
yes delete it div in html
