### ISSUE TITLE
Script does not start when server is restarted

### ISSUE THREAD

**Issue by spanxurazz** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#40]
Whenever I restart my server the script doesnt start I have have this error
![image](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/121069818/977d7b77-c681-46b9-89e7-cdf19ec866de)

Any way to fix it?

**Comment by spanxurazz** [comment]
Also I went to change the speed reader from kph to mph and it does not work

**Comment by rohKane** [comment]
Check your qbcore make your it's the latest version it's not my script fault
