### ISSUE TITLE
[BUG] Cop Stress

### ISSUE THREAD

**Issue by ChrizsTTV** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#42]
Hey,
I kinda noticed that the Cop Stress works with shooting but not with driving. I deleted the Stress Whitelist but Cops don't get Stress while driving by any chance.

**Comment by rohKane** [comment]
It's not the default qb core stress system right?

**Comment by rohKane** [comment]
Like I already mention this is a edited version of the original QBCore Hud so I only offer support to issues with my script

**Comment by ChrizsTTV** [comment]
But the Stress is build into the hud????

**Comment by rohKane** [comment]
Please try installing the original qb-hud back and see if the problem is still there or not

**Comment by ChrizsTTV** [comment]
So I tried it with the original qb hud AND with ps hud and both don't have the stress bug

**Comment by rohKane** [comment]
Where do you add that cops stress whitelist?

**Comment by ChrizsTTV** [comment]
I tried to remove the Whitelist for Cops so Cops get Stress. But they won't. In your edited Config the Cops are already whitelisted & I just removed it.

**Comment by rohKane** [comment]
hello maybe try set the job whitelist to false like this 
['police'] = false
in the config file and set Emergency vehicle class to true change this on line 76
['18'] = true,       -- Emergency

**Comment by ChrizsTTV** [comment]
The Vehicle Class was actually turned off for Stress, Thanks a lot and sorry that I didn't checked that earlier
