### ISSUE TITLE
4k not working

### ISSUE THREAD

**Issue by NickBroughton** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#43]
![Screenshot 2024-03-03 133501](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/88165525/4037be3c-5d5d-45cd-972c-73d7ab05541e)

Resolution: 3840X2160p

works on 2k and 3k now

**Comment by rohKane** [comment]
very sorry since I don't have a 4k display I won't be able to make it perfectly fit the screen can you try with my new update and see if it fit correctly or not

**Comment by NickBroughton** [comment]
Fixed! The only thing is the KPH is a little too high and conflicts with the fuel icon, but the speedometer is good now. Thanks
![Screenshot 2024-03-07 155919](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/88165525/7f940c3b-5ffd-463c-874f-b08b5ad40d34)

**Comment by rohKane** [comment]
can you check again now
