### ISSUE TITLE
Tiny Icons

### ISSUE THREAD

**Issue by Surge-Ricky** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#47]
The icons appear tiny. I'm on a 4k resolution. It seems you are using a hard font-size in the html instead of using EM's or percent scaling in CSS for the icons. They should scale according to screen resolution. I will try to make a fix myself if possible this weekend.

![imageasdfasdf](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/88600708/4d529fdd-52bc-4832-9e40-07c10181789a)

**Comment by rohKane** [comment]
you can change it yourself inside responsive.css since I don't have a 4k display i won't be able to fix it. it would be awesome if you can help us make it perfectly fit 4k screens.
