### ISSUE TITLE
warnings in F8 console CLIENT

### ISSUE THREAD

**Issue by Mariyan-Nikov** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#48]
everything is working just warning messages for clients when entering exiting vehicles that says cannot get vehicle status. I think the problem is that the X vehicle is not entered as manual car. For example i /car zentorno and says that it doesnt know whether the vehicle is A or Manual

**Comment by rohKane** [comment]
Already fixed

**Comment by rohKane** [comment]
Please download the latest release
