### ISSUE TITLE
-bug- Randomly being Teleported into civ vehicle

### ISSUE THREAD

**Issue by MrTeaRexx** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#50]
while being idle in the car for a long time, you will be teleported into a random civ car with the script saying: SET_VEHICLE_HIGH_GEAR: no such entity on default settings on a car that's auto

**Comment by rohKane** [comment]
Vod? How is that possible

**Comment by MrTeaRexx** [comment]
ill have a video up for ya later today

**Comment by rohKane** [comment]
It's definitely not because of the hud please check other resource because there's literally no code related to warp into vehicle code inside the script

**Comment by MrTeaRexx** [comment]
> It's definitely not because of the hud please check other resource because there's literally no code related to warp into vehicle code inside the script

literally not what i said.. SET_VEHICLE_HIGH_GEAR: no such entity on default settings on a car that's auto and because of this it teleports the player into a civ car.... i didn't mention anything about teleport code.... you have to sit idle for over 30mins for it to happen and im using the default qbcore barebone and still did it

**Comment by rohKane** [comment]
Alright show me a clip of it happening

**Comment by rohKane** [comment]
how can SET_VEHICLE_HIGH_GEAR native teleport a player into a civ car? bro lol

**Comment by rohKane** [comment]
> It's definitely not because of the hud please check other resource because there's literally no code related to warp into vehicle code inside the script

also what I said warp here means teleport

**Comment by rohKane** [comment]
No response **NOT A BUG**
