### ISSUE TITLE
BUG - menu ui 

### ISSUE THREAD

**Issue by gevo507** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#51]
hello,

i'm facing a problem when i open the menu then close it i cannot move or do anything and the mouse still on screen,
so maybe the menu not closing probable

also i have these in F8 :
![Screenshot_8](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/52261530/2ba70724-9ac4-490e-bce7-93e2f3194d19)

**Comment by rohKane** [comment]
It's working fine for me maybe it's because of your game try clearing your game cache
