### ISSUE TITLE
[BUG] Fulltunes

### ISSUE THREAD

**Issue by ChrizsTTV** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#52]
Hey I wanna inform you about a Bug with the script that I found out a hot minute ago. If you Full Tune your Car and get out, It fucks with the Full Tuning and the gears because of the HRSGear Plugin. After you get in the car again the car is way slower than it should be

**Comment by rohKane** [comment]
Is the car manual?

**Comment by ChrizsTTV** [comment]
No, thats the weird thing about it. EVERY Car has this bug. Doesnt matter if its manual or not

**Comment by rohKane** [comment]
It's definitely because of your mechanic script

**Comment by rohKane** [comment]
Try stop the hud then upgrade the vehicle and try again

**Comment by ChrizsTTV** [comment]
I did, same Bug. Using the original QB Hud or the ps hud the bug isnt there. So the Error lays inside HRSGears

**Comment by rohKane** [comment]
maybe just delete the hrsgears

**Comment by rohKane** [comment]
I fork it from a guy 3 years ago so it might not work as expected.

**Comment by rohKane** [comment]
and please tell me if the bug is still there or not thank you.

**Comment by ChrizsTTV** [comment]
I tried removing it but then my RPM Gauge is missing and the MPH is all over the place

**Comment by rohKane** [comment]
> Hey I wanna inform you about a Bug with the script that I found out a hot minute ago. If you Full Tune your Car and get out, It fucks with the Full Tuning and the gears because of the HRSGear Plugin. After you get in the car again the car is way slower than it should be

Can you give me a video of it happening please because i already tested it and there's nothing like you said here.

**Comment by ChrizsTTV** [comment]
Yeah I have to put it on the testserver, but I'll do it

**Comment by ChrizsTTV** [comment]
https://medal.tv/games/gta-v/clips/26rKeiLDKlIXQi/d1337pBspbog?invite=cr-MSxJWVksMjk5NzI0MTks

here is the clip. Idk if you can see it but my guess is that it removes the transmission upgrade from the cars after you leave it. Because, as you can see, you can see the suspension and hear the turbo.

**Comment by rohKane** [comment]
I still hear the turbo tho, have you tried checking the upgrades inside any customs mechanic yet? please check everything first before opening an issue because I already tested it using popcornrp-customs and all the upgrades are still there.

**Comment by ChrizsTTV** [comment]
please read my message again :D I said "I think that the HSRGears remove the transmission upgrade and change the transmission ratios what makes the car so slow. I even have a qb-hud High Gear Error in the end of the video because I removed both manual cars from the HRS Gears Config.

**Comment by rohKane** [comment]
Dude that's impossible you can check the code yourself where it's checking for manual vehicle there's literally nothing that could possibly causing this issue since your car is an automatic, alright now try delete the hrsgears.lua then test it again if you could sense the HSRGears remove the transmission upgrade and change the transmission ratios or not.

**Comment by rohKane** [comment]
and for the rpm hud messing up just don't care about it yet test the transmission first

**Comment by ChrizsTTV** [comment]
> Dude that's impossible you can check the code yourself where it's checking for manual vehicle there's literally nothing that could possibly causing this issue since your car is an automatic, alright now try delete the hrsgears.lua then test it again if you could sense the HSRGears remove the transmission upgrade and change the transmission ratios or not.

I already testet it, with the HRS Gears removed, the bug is gone

**Comment by ChrizsTTV** [comment]
So I doublechecked it. While having the crazy debuff it still says that the tuning is completely fine. Even Transmission is installed So it has to do something with either HSR Gears changing the Gear Ratios, or the tuning is installed without it working. Because the car is significantly slower.

**Comment by rohKane** [comment]
> https://medal.tv/games/gta-v/clips/26rKeiLDKlIXQi/d1337pBspbog?invite=cr-MSxJWVksMjk5NzI0MTks
> 
> here is the clip. Idk if you can see it but my guess is that it removes the transmission upgrade from the cars after you leave it. Because, as you can see, you can see the suspension and hear the turbo.

This is strange I'm not getting that error on my server are you sure you got my latest release script? please delete your current one then git clone the script again

**Comment by rohKane** [comment]
Ok so the SET_VEHICLE_HIGH_GEAR no such entity happens when you dv the car while you are still inside it, and it has nothing to do with gear ratio or Transmission so just ignore it. I already tested multiple cars I get out then get in and it's not slowed down like you said please get someone to test it with you.

**Comment by rohKane** [comment]
![image](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/47999933/325e5927-dd23-4a87-8ecc-60415c6437b1)

see here even the original fivem handling loader also freak out when you dv the car while inside it.

**Comment by rohKane** [comment]
Alright try my new update I've added checks manual for all of the loop.

**Comment by ChrizsTTV** [comment]
> ![image](https://private-user-images.githubusercontent.com/47999933/321244199-325e5927-dd23-4a87-8ecc-60415c6437b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTc1ODgsIm5iZiI6MTcxMjc1NzI4OCwicGF0aCI6Ii80Nzk5OTkzMy8zMjEyNDQxOTktMzI1ZTU5MjctZGQyMy00YTg3LThlY2MtNjA0MTVjNjQzN2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEzNTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwOTIwODY3MjU0OGNjOWZlZGZhNjAwMmI4MDAwMDViYmFmNmUzYWUzODQwZjg1MjQyNGNlODYwYTc1NmRjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.laudUWhRewgYLmOZH4JIKB6mQZcgvEPf5Yv0YVgnHaM)
> 
> see here even the original fivem handling loader also freak out when you dv the car while inside it.

Yea I know but I dont mean the handling-loader. I literally had an qb-hud error that said "high gear error"

**Comment by rohKane** [comment]
> > ![image](https://private-user-images.githubusercontent.com/47999933/321244199-325e5927-dd23-4a87-8ecc-60415c6437b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTc1ODgsIm5iZiI6MTcxMjc1NzI4OCwicGF0aCI6Ii80Nzk5OTkzMy8zMjEyNDQxOTktMzI1ZTU5MjctZGQyMy00YTg3LThlY2MtNjA0MTVjNjQzN2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEzNTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwOTIwODY3MjU0OGNjOWZlZGZhNjAwMmI4MDAwMDViYmFmNmUzYWUzODQwZjg1MjQyNGNlODYwYTc1NmRjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.laudUWhRewgYLmOZH4JIKB6mQZcgvEPf5Yv0YVgnHaM)
> > see here even the original fivem handling loader also freak out when you dv the car while inside it.
> 
> Yea I know but I dont mean the handling-loader. I literally had an qb-hud error that said "high gear error"

bro read my message again

**Comment by rohKane** [comment]
> > ![image](https://private-user-images.githubusercontent.com/47999933/321244199-325e5927-dd23-4a87-8ecc-60415c6437b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTc1ODgsIm5iZiI6MTcxMjc1NzI4OCwicGF0aCI6Ii80Nzk5OTkzMy8zMjEyNDQxOTktMzI1ZTU5MjctZGQyMy00YTg3LThlY2MtNjA0MTVjNjQzN2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEzNTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwOTIwODY3MjU0OGNjOWZlZGZhNjAwMmI4MDAwMDViYmFmNmUzYWUzODQwZjg1MjQyNGNlODYwYTc1NmRjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.laudUWhRewgYLmOZH4JIKB6mQZcgvEPf5Yv0YVgnHaM)
> > see here even the original fivem handling loader also freak out when you dv the car while inside it.
> 
> Yea I know but I dont mean the handling-loader. I literally had an qb-hud error that said "high gear error"

I literally said it's not an error it's because you dv the vehicle while you're inside it so just ignore the error ok??

**Comment by rohKane** [comment]
> ![image](https://private-user-images.githubusercontent.com/47999933/321244199-325e5927-dd23-4a87-8ecc-60415c6437b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTc2NDcsIm5iZiI6MTcxMjc1NzM0NywicGF0aCI6Ii80Nzk5OTkzMy8zMjEyNDQxOTktMzI1ZTU5MjctZGQyMy00YTg3LThlY2MtNjA0MTVjNjQzN2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEzNTU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYWVjMDM5ZmVmZjQyYzRiYjYwNTUwYzhjMTEzYTdiYjkwNDhiMWU1NmJmNDdjY2UwN2U1MjFmYWM2ZTQ2MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QJShZVHeHKw1fvyp7FP0SIaWNfarD0miwGFCQv59h6I)
> 
> see here even the original fivem handling loader also freak out when you dv the car while inside it.

I sent you this screenshot to let you know that even FIVEM NATIVE handling loader freak out when you dv the vehicle while you're inside it. it's just that my script prints it out and this handling loader error prints out to canary game build only.

**Comment by ChrizsTTV** [comment]
![Bild_2024-04-10_160048657](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/149575440/e8451363-b691-49cc-9374-58a625e23f32)


Nah I get this one without dv'ing anything. It gets in the console the second I get out of the car.

**Comment by ChrizsTTV** [comment]
Bug is still there :(

**Comment by ChrizsTTV** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/47999933/321244199-325e5927-dd23-4a87-8ecc-60415c6437b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTc1ODgsIm5iZiI6MTcxMjc1NzI4OCwicGF0aCI6Ii80Nzk5OTkzMy8zMjEyNDQxOTktMzI1ZTU5MjctZGQyMy00YTg3LThlY2MtNjA0MTVjNjQzN2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDEzNTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwOTIwODY3MjU0OGNjOWZlZGZhNjAwMmI4MDAwMDViYmFmNmUzYWUzODQwZjg1MjQyNGNlODYwYTc1NmRjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.laudUWhRewgYLmOZH4JIKB6mQZcgvEPf5Yv0YVgnHaM)
> > > see here even the original fivem handling loader also freak out when you dv the car while inside it.
> > 
> > 
> > Yea I know but I dont mean the handling-loader. I literally had an qb-hud error that said "high gear error"
> 
> I literally said it's not an error it's because you dv the vehicle while you're inside it so just ignore the error ok??

Ah sry

**Comment by rohKane** [comment]
> Bug is still there :(

I had 2 of my friends testing it and they all said they notice no differences. so hmm it's kinda strange.

**Comment by rohKane** [comment]
The up shift time still the same and the top speed is also the same I tested it with sultanrs.

**Comment by ChrizsTTV** [comment]
> > Bug is still there :(
> 
> I had 2 of my friends testing it and they all said they notice no differences. so hmm it's kinda strange.

I can invite you to test it if you want

**Comment by rohKane** [comment]
> > > Bug is still there :(
> > 
> > 
> > I had 2 of my friends testing it and they all said they notice no differences. so hmm it's kinda strange.
> 
> I can invite you to test it if you want

have you tried delete your current qb-hud script? don't replace it you have to delete it then drag the new one in

**Comment by ChrizsTTV** [comment]
> > > > Bug is still there :(
> > > 
> > > 
> > > I had 2 of my friends testing it and they all said they notice no differences. so hmm it's kinda strange.
> > 
> > 
> > I can invite you to test it if you want
> 
> have you tried delete your current qb-hud script? don't replace it you have to delete it then drag the new one in

Yes I fully deleted it, put the new one in and restarted the testserver

**Comment by ChrizsTTV** [comment]
Any Updates to this? Or can you maybe make a version without the HRSGears

**Comment by ChrizsTTV** [comment]
I noticed: You are faster than a non tuned car but slower than a full tuned car

**Comment by ChrizsTTV** [comment]
I just removed the resetvehicle function in hrsgears.lua and the bug is gone

**Comment by ChrizsTTV** [comment]
It removes the last gear thats why the cars are so slow...

**Comment by rohKane** [comment]
> I just removed the resetvehicle function in hrsgears.lua and the bug is gone

Glad it worked for you, I've never noticed this bug at all tested multiple times with multiple people and they didn't notice it either so I'm going to close this now.
