### ISSUE TITLE
ox_fuel issue

### ISSUE THREAD

**Issue by stag260rs** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#56]
Cant seem to get the rest of the hud to show up. im using the ox_fuel ive tried changing the line of code to ox_fuel as i can see its using legacy fuel. still doesnt work is there a way around this
![Screenshot (558)](https://github.com/rohKane/Kane-qb-hud-Nopixel-4.0-inspired/assets/174689465/0fcddb10-380c-4e37-a936-b78475ff2795)

**Comment by rohKane** [comment]
You can try create the getfuel function yourself in ox_fuel but this script is for LegacyFuel

**Comment by rohKane** [comment]
Entity(entity).state.fuel found this function to get fuel in ox_fuel maybe try replacing it with the legacy get fuel

**Comment by stag260rs** [comment]
ill sus that out also cant seem to find it in the scripts but is there a toggle to turn off and turn on manual gears for players that dont want to use manual gears and preffer automatic

**Comment by rohKane** [comment]
Yes please read our readme
