### ISSUE TITLE
hud change (not an issue)

### ISSUE THREAD

**Issue by Griefa** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#7]
hey, 

Just wondering where abouts in the CSS do I make the HUD (health, armor etc) closer together?

**Comment by Griefa** [comment]
I saw this

```
.q-ml-xl {
    margin-left: -50px !important; /* Change this to space radials */
}``` 

but it doesnt change at all

**Comment by rohKane** [comment]
Change it in html for each of the show bar.

**Comment by Griefa** [comment]
> Change it in html for each of the show bar.

Thank you :)

Another thing I noticed too is when the vehicle is damaged the Engine bar doesnt change [colour](https://i.imgur.com/5LZ9l7o.png).

 Here is the [error](https://i.imgur.com/5LZ9l7o.png)
