### ISSUE TITLE
Passenger POV Issues. Not sync with driver POV.

### ISSUE THREAD

**Issue by SarangGit** [rohKane/Kane-qb-hud-Nopixel-4.0-inspired#8]
1. Gear always shown as N in manual mode for passengers.

2. Car Sound for passenger is always like car is in Red RPM. Also visually RPM bar is at top, at red.

**Comment by rohKane** [comment]
Can you show me the video of it happening please.

**Comment by rohKane** [comment]
Since you don't reply i will have to close this.
